duration:
  connection:
    address: tcp:host=192.168.1.19,port=8888
  message:
    interface: org.neutrino.audiomatic.daemon
    path: /Launcher
    member: org.neutrino.audiomatic.Daemon.Launcher.StartProcessor
    arguments:
      - INPUT
      - OUTPUT
